version: '3'
services:
  web:
    build: .
    ports:
    - "3000:3000"
    links:
    - db
  db:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
