// Code generated by MockGen. DO NOT EDIT.
// Source: bvc/persistence.go

// Package mock_bvc is a generated GoMock package.
package bvc

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/julianespinel/mila-api/models"
)

// MockPersistenceInterface is a mock of PersistenceInterface interface
type MockPersistenceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPersistenceInterfaceMockRecorder
}

// MockPersistenceInterfaceMockRecorder is the mock recorder for MockPersistenceInterface
type MockPersistenceInterfaceMockRecorder struct {
	mock *MockPersistenceInterface
}

// NewMockPersistenceInterface creates a new mock instance
func NewMockPersistenceInterface(ctrl *gomock.Controller) *MockPersistenceInterface {
	mock := &MockPersistenceInterface{ctrl: ctrl}
	mock.recorder = &MockPersistenceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPersistenceInterface) EXPECT() *MockPersistenceInterfaceMockRecorder {
	return m.recorder
}

// CountStocks mocks base method
func (m *MockPersistenceInterface) CountStocks() int {
	ret := m.ctrl.Call(m, "CountStocks")
	ret0, _ := ret[0].(int)
	return ret0
}

// CountStocks indicates an expected call of CountStocks
func (mr *MockPersistenceInterfaceMockRecorder) CountStocks() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountStocks", reflect.TypeOf((*MockPersistenceInterface)(nil).CountStocks))
}

// SaveStocks mocks base method
func (m *MockPersistenceInterface) SaveStocks(stocks []models.Stock) error {
	ret := m.ctrl.Call(m, "SaveStocks", stocks)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveStocks indicates an expected call of SaveStocks
func (mr *MockPersistenceInterfaceMockRecorder) SaveStocks(stocks interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveStocks", reflect.TypeOf((*MockPersistenceInterface)(nil).SaveStocks), stocks)
}
