// Code generated by MockGen. DO NOT EDIT.
// Source: bvc/persistence.go

// Package bvc is a generated GoMock package.
package bvc

import (
	gomock "github.com/golang/mock/gomock"
	models "github.com/julianespinel/mila-api/models"
	reflect "reflect"
)

// MockPersistenceMila is a mock of PersistenceMila interface
type MockPersistenceMila struct {
	ctrl     *gomock.Controller
	recorder *MockPersistenceMilaMockRecorder
}

// MockPersistenceMilaMockRecorder is the mock recorder for MockPersistenceMila
type MockPersistenceMilaMockRecorder struct {
	mock *MockPersistenceMila
}

// NewMockPersistenceMila creates a new mock instance
func NewMockPersistenceMila(ctrl *gomock.Controller) *MockPersistenceMila {
	mock := &MockPersistenceMila{ctrl: ctrl}
	mock.recorder = &MockPersistenceMilaMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPersistenceMila) EXPECT() *MockPersistenceMilaMockRecorder {
	return m.recorder
}

// countStocks mocks base method
func (m *MockPersistenceMila) countStocks() int {
	ret := m.ctrl.Call(m, "countStocks")
	ret0, _ := ret[0].(int)
	return ret0
}

// countStocks indicates an expected call of countStocks
func (mr *MockPersistenceMilaMockRecorder) countStocks() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "countStocks", reflect.TypeOf((*MockPersistenceMila)(nil).countStocks))
}

// saveStocks mocks base method
func (m *MockPersistenceMila) saveStocks(stocks []models.Stock) error {
	ret := m.ctrl.Call(m, "saveStocks", stocks)
	ret0, _ := ret[0].(error)
	return ret0
}

// saveStocks indicates an expected call of saveStocks
func (mr *MockPersistenceMilaMockRecorder) saveStocks(stocks interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "saveStocks", reflect.TypeOf((*MockPersistenceMila)(nil).saveStocks), stocks)
}

// getCurrentDayStocks mocks base method
func (m *MockPersistenceMila) getCurrentDayStocks(country string) []models.Stock {
	ret := m.ctrl.Call(m, "getCurrentDayStocks", country)
	ret0, _ := ret[0].([]models.Stock)
	return ret0
}

// getCurrentDayStocks indicates an expected call of getCurrentDayStocks
func (mr *MockPersistenceMilaMockRecorder) getCurrentDayStocks(country interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getCurrentDayStocks", reflect.TypeOf((*MockPersistenceMila)(nil).getCurrentDayStocks), country)
}
